// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfvhYd_2rn8c-AgFj5lQxo7ExD9TFQAIg',
    appId: '1:835290094074:web:f05861e2891e111ebfec43',
    messagingSenderId: '835290094074',
    projectId: 'achizitiicereale-f6819',
    authDomain: 'achizitiicereale-f6819.firebaseapp.com',
    databaseURL: 'https://achizitiicereale-f6819-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'achizitiicereale-f6819.appspot.com',
    measurementId: 'G-CYN04EJ52M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVpDg1doSpF4vyNZNjk4MCRO3PRBvz7I',
    appId: '1:835290094074:android:33ecc354434e2f62bfec43',
    messagingSenderId: '835290094074',
    projectId: 'achizitiicereale-f6819',
    databaseURL: 'https://achizitiicereale-f6819-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'achizitiicereale-f6819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkVcv62vDFYTAIyoCxRbfXzlSjjoP--A',
    appId: '1:835290094074:ios:62bcaabe0d81425dbfec43',
    messagingSenderId: '835290094074',
    projectId: 'achizitiicereale-f6819',
    databaseURL: 'https://achizitiicereale-f6819-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'achizitiicereale-f6819.appspot.com',
    iosClientId: '835290094074-ciotrim2oqifoqirvjdv3gf1oumsejar.apps.googleusercontent.com',
    iosBundleId: 'ro.fastapp.achizitiiCereale',
  );
}
